export enum getUserDetailByIdEnum {
  FAILED_TO_GET_USER_DETAIL = "FAILED_TO_GET_USER_DETAIL",
  FOUND_USER_DETAIL = "FOUND_USER_DETAIL",
}

export enum AuthFailedEnum {
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}
