export enum getUserProfilePictureEnum {
  FAILED_TO_GET_PROFILE_PICTURE = "FAILED_TO_GET_PROFILE_PICTURE",
  GOT_PROFILE_PICTURE = "GOT_PROFILE_PICTURE",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}

export enum collectImageEnum {
  COLLECTION_IMAGE_FAILED = "COLLECTION_IMAGE_FAILED",
  NEW_COLLECTION_CREATED = "NEW_COLLECTION_CREATED",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  COLLECTION_UPDATED = "COLLECTION_UPDATED",
  COLLECTION_REMOVED = "COLLECTION_REMOVED",
}
