export enum getUserProfilePictureEnum {
  FAILED_TO_GET_PROFILE_PICTURE = "FAILED_TO_GET_PROFILE_PICTURE",
  GOT_PROFILE_PICTURE = "GOT_PROFILE_PICTURE",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}

export enum collectImageEnum {
  COLLECTION_IMAGE_FAILED = "COLLECTION_IMAGE_FAILED",
  NEW_COLLECTION_CREATED = "NEW_COLLECTION_CREATED",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  COLLECTION_UPDATED = "COLLECTION_UPDATED",
  COLLECTION_REMOVED = "COLLECTION_REMOVED",
}

export enum getCollectionImagesIdsEnum {
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  COLLECTION_NAMES_IDS = "COLLECTION_NAMES_IDS",
  FAILED_TO_RETRIVE_COLLECTION_NAME_IDS = "FAILED_TO_RETRIVE_COLLECTION_NAME_IDS",
}

export enum getImageByIdEnum {
  FAILED_TO_GET_IMAGE = "FAILED_TO_GET_IMAGE",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  USER_IMAGE = "USER_IMAGE",

}