export enum collectImageEnum {
  COLLECTION_IMAGE_FAILED = "COLLECTION_IMAGE_FAILED",
  NEW_COLLECTION_CREATED = "NEW_COLLECTION_CREATED",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  COLLECTION_UPDATED = "COLLECTION_UPDATED",
  COLLECTION_REMOVED = "COLLECTION_REMOVED",
}

export enum getCollectionImagesIdsEnum {
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  COLLECTION_NAMES_IDS = "COLLECTION_NAMES_IDS",
  FAILED_TO_RETRIVE_COLLECTION_NAME_IDS = "FAILED_TO_RETRIVE_COLLECTION_NAME_IDS",
}

export enum getCollectionNameByIdEnum {
  FAILED_TO_RETRIVE_COLLECTION_NAME_BY_ID = "FAILED_TO_RETRIVE_COLLECTION_NAME_BY_ID",
  COLLECTION_NAMES_RETRIVED = "COLLECTION_NAMES_RETRIVED",
  COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND",
}

export enum changeCollectionNameEnum {
  FAILED_TO_CHANGE_COLLECTION_NAME = "FAILED_TO_CHANGE_COLLECTION_NAME",
  COLLECTION_NAME_CHANGED = "COLLECTION_NAME_CHANGED",
}

export enum deleteCollectionNameEnum {
  FAILED_TO_DELETE_COLLECTION_NAME = "FAILED_TO_DELETE_COLLECTION_NAME",
  COLLECTION_NAME_DELETED = "COLLECTION_NAME_DELETED",
}

export enum deleteAccountByUserIdEnum {
  FAILED_TO_DELETE_ACCOUNT = "FAILED_TO_DELETE_ACCOUNT",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
}

export enum createTokenForUserAccountDeletionEnum {
  FAILED_TO_CREATE_TOKEN = "FAILED_TO_CREATE_TOKEN",
  TOKEN_CREATED = "TOKEN_CREATED",
}

export enum updateUserDetailEnum {
  FAILED_TO_UPDATE_USER = "FAILED_TO_UPDATE_USER",
  USER_UPDATED = "USER_UPDATED",
}

export enum getUserDetailByIdEnum {
  FAILED_TO_GET_USER_DETAIL = "FAILED_TO_GET_USER_DETAIL",
  FOUND_USER_DETAIL = "FOUND_USER_DETAIL",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}

export enum updateUserProfilePictureEnum {
  FAILED_TO_UPDATE_PROFILE_PICTURE = "FAILED_TO_UPDATE_PROFILE_PICTURE",
  PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}

export enum getUserProfilePictureEnum {
  FAILED_TO_GET_PROFILE_PICTURE = "FAILED_TO_GET_PROFILE_PICTURE",
  GOT_PROFILE_PICTURE = "GOT_PROFILE_PICTURE",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}

export enum createImagesEnum {
  FAILED_TO_CREATE_IMAGES = "FAILED_TO_CREATE_IMAGES",
  IMAGE_CREATED = "IMAGE_CREATED",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  DAILY_COUNT_EXCEDDED = "DAILY_COUNT_EXCEDDED",
}

export enum getDailyUploadCountEnum {
  FAILED_TO_GET_UPLOAD_COUNT = "FAILED_TO_GET_UPLOAD_COUNT",
  UPLOAD_COUNT = "UPLOAD_COUNT",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
}

export enum getImagesEnum {
  FAILED_TO_GET_IMAGES = "FAILED_TO_GET_IMAGES",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  USER_IMAGES = "USER_IMAGES",
}

export enum getImageByIdEnum {
  FAILED_TO_GET_IMAGE = "FAILED_TO_GET_IMAGE",
  USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
  USER_IMAGE = "USER_IMAGE",
}
