export enum CreateTokenForUserAccountDeletionEnum {
  FAILED_TO_CREATE_TOKEN = "FAILED_TO_CREATE_TOKEN",
  TOKEN_CREATED = "TOKEN_CREATED",
}

export enum DeleteAccountByUserIdEnum {
  FAILED_TO_DELETE_ACCOUNT = "FAILED_TO_DELETE_ACCOUNT",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
}
