export enum CollectImageEnum {
  COLLECTION_IMAGE_FAILED = "COLLECTION_IMAGE_FAILED",
  NEW_COLLECTION_CREATED = "NEW_COLLECTION_CREATED",
  COLLECTION_UPDATED = "COLLECTION_UPDATED",
  COLLECTION_REMOVED = "COLLECTION_REMOVED",
}
