export enum CollectVideosIdsEnum {
  FAILED_TO_COLLECT_VIDEOS_IDS = "FAILED_TO_COLLECT_VIDEOS_IDS",
  VIDEO_IDS_COLLECTED = "VIDEO_IDS_COLLECTED",
}

export enum CollectVideoEnum {
  COLLECTION_VIDEO_FAILED = "COLLECTION_VIDEO_FAILED",
  NEW_COLLECTION_CREATED = "NEW_COLLECTION_CREATED",
  COLLECTION_UPDATED = "COLLECTION_UPDATED",
  COLLECTION_REMOVED = "COLLECTION_REMOVED",
}
