export enum GetLikedVideosEnum {
  GOT_LIKED_VIDEO = "GOT_LIKED_VIDEO",
  FAILED_TO_GET_LIKED_VIDEO = "FAILED_TO_GET_LIKED_VIDEO",
}

export enum LikeVideoEnum {
  VIDEO_LIKED = "VIDEO_LIKED",
  VIDEO_UNLIKED = "VIDEO_UNLIKED",
  FAILED_TO_LIKE_VIDEO = "FAILED_TO_LIKE_VIDEO",
}
