export enum LikeImageEnum {
  IMAGE_LIKED = "IMAGE_LIKED",
  IMAGE_UNLIKED = "IMAGE_UNLIKED",
  FAILED_TO_LIKE_PHOTO = "FAILED_TO_LIKE_PHOTO",
}

export enum GetLikedImagesEnum {
  GOT_LIKED_PHOTO = "GOT_LIKED_PHOTO",
  FAILED_TO_GET_LIKED_PHOTO = "FAILED_TO_GET_LIKED_PHOTO",
}
