export enum getPexelPhotoByIdEnum {
  FOUND_PHOTOS = "FOUND_PHOTOS",
  NOT_PHOTO_TYPE = "NOT_PHOTO_TYPE",
  NULL = "NULL",
}

export enum GetRandomPhotoEnum {
  PHOTO_FOUND = "PHOTO_FOUND",
  FAILED_TO_GET_RANDOM_PHOTO = "FAILED_TO_GET_RANDOM_PHOTO",
}
