export enum getPexelVideoByIdEnum {
  FOUND_VIDEOS = "FOUND_VIDEOS",
  NOT_VIDEO_TYPE = "NOT_VIDEO_TYPE",
  NULL = "NULL",
}

export enum GetVideosEnum {
  VIDEOS_FOUND = "VIDEOS_FOUND",
  FAILED_TO_GET_ALL_VIDEOS = "FAILED_TO_GET_ALL_VIDEOS",
}

export enum GetVideosByKeywordEnum {
  VIDEOS_FOUND = "VIDEOS_FOUND",
  FAILED_TO_GET_VIDEOS = "FAILED_TO_GET_VIDEOS",
}

export enum GetRandomVideoEnum {
  VIDEO_FOUND = "VIDEO_FOUND",
  FAILED_TO_GET_RANDOM_VIDEO = "FAILED_TO_GET_RANDOM_VIDEO",
}
