export enum GetUserProfilePictureEnum {
  FAILED_TO_GET_PROFILE_PICTURE = "FAILED_TO_GET_PROFILE_PICTURE",
  GOT_PROFILE_PICTURE = "GOT_PROFILE_PICTURE",
}

export enum GetPublicProfilePictureEnum {
  FAILED_TO_GET_PROFILE_PICTURE = "FAILED_TO_GET_PROFILE_PICTURE",
  GOT_PROFILE_PICTURE = "GOT_PROFILE_PICTURE",
}
