export enum UpdateUserDetailEnum {
  FAILED_TO_UPDATE_USER = "FAILED_TO_UPDATE_USER",
  USER_UPDATED = "USER_UPDATED",
}
export enum UpdateUserProfilePictureEnum {
  FAILED_TO_UPDATE_PROFILE_PICTURE = "FAILED_TO_UPDATE_PROFILE_PICTURE",
  PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED",
}
